/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import static connect.connectoDB.conn;
import static frontend.Shop.billno;
import static frontend.Transaction.method;
import static frontend.Transaction.transItems;
import static frontend.Transaction.transactionid;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import receipt.Items;

/**
 *
 * @author beauty
 */
public class Receipt extends javax.swing.JFrame {
    public String street;
    public String areacode;
    public String city;
    public String branchName;
    public String phone;
    public int transactionId;
    public double total;
    public double change;
    public double amontpaid;
    public int billno;
    public int paymentmethod;
    public double tax;
    ArrayList<Items> MethodList1= new ArrayList<>();
    /**
     * Creates new form Receipt
     */
    public Receipt() {
        initComponents();
        getTransDetails();
        getBranchDetails();
        MethodList1 = transItems();
        writeItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        close.setText("Close");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(close)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(close)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        Welcome wel = new Welcome();
        this.setVisible(false);
        wel.setVisible(true);
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }
    public void writeItems(){
        jTextArea1.setText("----------------------------------------------------------\n");
        jTextArea1.append("The FoodHall"+ branchName+"\n");
        jTextArea1.append("Bill No:"+billno+"\n");
        jTextArea1.append("-----------------------------------------------------------\n");
        for (Items item1 : MethodList1){
            jTextArea1.append(item1.getItemname()+"  X   "+item1.getQuantity()+"   Rp "+item1.getItemPrice()+"\n");
        }
        jTextArea1.append("-----------------------------------------------------------\n");
        jTextArea1.append("-----------------------------------------------------------\n");
        jTextArea1.append("Total DUE           "+(total+(0.10*total))+"\n");
        jTextArea1.append("-----------------------------------------------------------\n");
        jTextArea1.append("-----------------------------------------------------------\n");
        jTextArea1.append("Sub Total           "+total+"\n");
        jTextArea1.append("Tax(10%)        "+ (total*0.10)+"\n");
        jTextArea1.append("-----------------------------------------------------------\n");
        jTextArea1.append(method + "           "+(total+(0.10*total))+"\n");
        jTextArea1.append("Change           "+change+"\n");
        jTextArea1.append("-----------------------------------------------------------\n");
        jTextArea1.append("SPECIAL OFFERS ONLY FOR CARDHOLDERS\n");
        jTextArea1.append("            "+street+" \n");
        jTextArea1.append("            "+phone+" \n");
        jTextArea1.append("-----------------------------------------------------------\n");
        
        
        
    }
    public void getBranchDetails(){
        try {
            String sql = "select * from branch where branchName='Senayan City'" ;
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next()) {
                branchName = resultSet.getString("branchName");
                street = resultSet.getString("address");
                phone = resultSet.getString("branchPhoneNum");
            }
            
            return;
            } 
        catch (SQLException ex) {
            ex.printStackTrace();
        }
        return;
    
    }
    public void getTransDetails(){
        try {
            String sql = "select * from transaction where transactionId="+transactionid ;
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next()) {
                total = resultSet.getDouble("total_price");
                amontpaid = resultSet.getDouble("amount_paid");
                billno = resultSet.getInt("FK_billNo");
                paymentmethod =resultSet.getInt("FK_paymentMethodId");
                tax =resultSet.getDouble("tax");
                change =resultSet.getDouble("change_");
            }
            
            return;
            } 
        catch (SQLException ex) {
            ex.printStackTrace();
        }
        return;
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
